tex:
	pdflatex apresentacao-tg-rcaf.tex
	pdflatex apresentacao-tg-rcaf.tex

view:
	gnome-open apresentacao-tg-rcaf.pdf

# Usage:
#
# make tex
# make view
#
# I didn't make a rule that does all of it once, so I can read error messages in each separated step.
#

.PHONY: tex view

